# Generated by Django 4.1.1 on 2023-08-11 20:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='subtitulo',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='cuerpo',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
