# Generated by Django 4.1.1 on 2023-08-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_autor_publicacion_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicacion',
            new_name='Post',
        ),
    ]
