# Generated by Django 4.1.1 on 2023-08-27 05:43

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_publicacion_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
