# Generated by Django 4.1.1 on 2023-08-16 18:25

from django.db import migrations, models
import lkinpractice.models
import lkinpractice.myfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_val', models.CharField(max_length=10, validators=[lkinpractice.models.validate_no_bad_words])),
                ('favorite_color', lkinpractice.myfields.RGBColorField(max_length=6, null=True)),
            ],
        ),
    ]
